name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build project
        run: ./gradlew build
        env:
          VERSION: ${{ github.ref }}
      - run: |
          assetsAAR=$(find . -name *release.aar | while read -r asset ; do echo "-a $asset" ; done)
          VERSION=$(echo $VERSION | cut -d'/' -f3)
          assetsJAR=$(find . -name *${VERSION}*.jar | while read -r asset ; do echo "-a $asset" ; done)
          tag_name="${GITHUB_REF##*/}"
          hub release create ${assetsAAR} ${assetsJAR} -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish
        uses: burrunan/gradle-cache-action@v1.6
        with:
          remote-build-cache-proxy-enabled: false
          properties: |
            gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
            gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
          arguments: publishPlugins -s --scan
