name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build project
        run: ./gradlew build
        env:
          VERSION: ${{ github.ref }}
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          commit-ish: HEAD
      - run: |
          assets=$(find . -name "*${{steps.tagger.outputs.tag#v}}*.jar" -or -name " *release.aar" | while read -r asset ; do echo "-a $asset" ; done)
          hub release create ${assets} -m "${{steps.tagger.outputs.tag}}" "${{steps.tagger.outputs.tag}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{steps.tagger.outputs.tag}}
      - name: Publish ${{steps.tagger.outputs.tag}}
        uses: burrunan/gradle-cache-action@v1.6
        with:
          remote-build-cache-proxy-enabled: false
          properties: |
            gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
            gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
          arguments: publishPlugins -s --scan
